name: stkplugin
description: plugin
display-name: stkplugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies:
  - "Api"
types:
  - app
hooks:
  - type: edit
    path: alerts.xml
    trigger: after-render
    changes:
      - search:
          string: "### NOVOS ALERTAS ACIMA ###"
          insert-before:
            snippet: 
          when:
            not-exists-snippet: 
